export interface Question {
  id: number;
  text: string;
  options: string[];
  correctAnswer: number; // index 0-3
}

export const questions: Question[] = [
  {
    id: 1,
    text: "Gandhi retained his false notion about handwriting till",
    options: [
      "he went to Africa",
      "he went to England and then to Africa",
      "he went to the school",
      "he went to his village",
    ],
    correctAnswer: 1,
  },
  {
    id: 2,
    text: "Gandhi was ashamed of himself when he saw the beautiful handwriting of lawyers and young men born and educated in",
    options: ["Gujarat", "Rajkot", "England", "South Africa"],
    correctAnswer: 3,
  },
  {
    id: 3,
    text: "Who, according to Gandhi, was a hard task master at the high school?",
    options: [
      "The English teacher",
      "The Persian teacher",
      "The Physical Education teacher",
      "The Sanskrit teacher",
    ],
    correctAnswer: 3,
  },
  {
    id: 4,
    text: "Who came to grief when Gandhi sat in the Persian class?",
    options: [
      "The Headmaster",
      "The Sanskrit teacher",
      "The class teacher",
      "The Science teacher",
    ],
    correctAnswer: 1,
  },
  {
    id: 5,
    text: "\"Why don't you learn the language of your own religion?\" Who is the speaker here?",
    options: [
      "Krishna Sankar Pandya",
      "Mr. Sorabji Edulji Gimi",
      "Gandhi himself",
      "The Persian teacher",
    ],
    correctAnswer: 0,
  },
  {
    id: 6,
    text: "Gandhi deeply regretted that he couldn't acquire a more thorough knowledge of",
    options: [
      "English language",
      "Sanskrit language",
      "Good handwriting",
      "Geography",
    ],
    correctAnswer: 1,
  },
  {
    id: 7,
    text: "Pick out a word from the passage that is similar in meaning to 'course of study in a school or a college'",
    options: ["Curriculum", "Certificate", "Proficiency", "Calendar"],
    correctAnswer: 0,
  },
  {
    id: 8,
    text: "What, according to Gandhi, leads to adverse physical, psychological and educational outcomes in the classrooms?",
    options: [
      "Physical training",
      "Mental training",
      "Physical disciplining",
      "Corporal punishment",
    ],
    correctAnswer: 3,
  },
  {
    id: 9,
    text: "What, according to Gandhi, was the most common punishment to the small children to cause pain in response to their behaviour?",
    options: [
      "Corporal punishment",
      "Psychological stress",
      "Mental harassment",
      "Legal punishment",
    ],
    correctAnswer: 0,
  },
  {
    id: 10,
    text: "The Headmaster used corporal punishment on Gandhi out of his desire for",
    options: ["Obedience", "Aggression", "Emotional response", "None of the above"],
    correctAnswer: 0,
  },
  {
    id: 11,
    text: "Who was a disciplinarian at the high school where Gandhi was a student?",
    options: [
      "The Sanskrit teacher",
      "The Headmaster",
      "The Persian teacher",
      "The classical teacher",
    ],
    correctAnswer: 1,
  },
  {
    id: 12,
    text: "Find a single word which means 'the story of a person written by that person' is called",
    options: ["Biography", "Autobiography", "Memoir", "Profile"],
    correctAnswer: 1,
  },
  {
    id: 13,
    text: "Which of the following books is not written by Gandhiji?",
    options: [
      "My Experiments with Truth",
      "Indian Home Rule",
      "Hind Swaraj",
      "The Golden Threshold",
    ],
    correctAnswer: 3,
  },
  {
    id: 14,
    text: "What is the nick name of Gandhi during his childhood?",
    options: ["Moniya", "Saina", "Karam", "Chand"],
    correctAnswer: 0,
  },
  {
    id: 15,
    text: "Gandhi's Sanskrit teacher Krishna Shankar Pandya placed strong emphasis on to motivate Gandhi towards Sanskrit class.",
    options: ["Violence", "Religion", "Literature", "Interest"],
    correctAnswer: 1,
  },
  {
    id: 16,
    text: "Gandhi very jealously guarded his character when he was a student at the high school. Gandhi thought is a sin.",
    options: [
      "Knowledge without character",
      "Politics without principle",
      "Science without humanity",
      "Pleasure without conscience",
    ],
    correctAnswer: 0,
  },
  {
    id: 17,
    text: "Find out a word from the passage similar in meaning to 'begin'.",
    options: ["Convict", "Commence", "Considerate", "Exempt"],
    correctAnswer: 1,
  },
  {
    id: 18,
    text: "In which standard did Gandhi become disheartened?",
    options: ["Standard-3", "Standard-4", "Standard-5", "Standard-6"],
    correctAnswer: 3,
  },
  {
    id: 19,
    text: "The Persian teacher was an effective teacher because",
    options: [
      "He provided a student centered environment in the classroom",
      "He knew how to handle the class",
      "He had the ability to develop trusting and productive relationship among the students",
      "All the above",
    ],
    correctAnswer: 3,
  },
  {
    id: 20,
    text: "Why, according to Gandhi, did all the boys at the high school obey and honour their headmaster Mr. Dorabji Edulji Gimi?",
    options: [
      "Mr. Gimi was a good teacher",
      "Mr. Gimi was a man of method",
      "Mr. Gimi was just like a sage on the stage",
      "All the above",
    ],
    correctAnswer: 3,
  },
  {
    id: 21,
    text: "Which of the following statement is not suitable for the Persian teacher?",
    options: [
      "He introduced student centred approach to learning.",
      "He followed teacher centred approach to learning.",
      "He was like a guide on the side of the students.",
      "He forced the students to learn everything by heart.",
    ],
    correctAnswer: 3,
  },
  {
    id: 22,
    text: "Who, according to Gandhi, tried himself to be more successful than other teachers?",
    options: [
      "The Sanskrit teacher",
      "The Headmaster",
      "The Persian teacher",
      "None of the above",
    ],
    correctAnswer: 0,
  },
  {
    id: 23,
    text: "Find out a word in similar meaning to a person who competes with another for the same objective.",
    options: ["Adviser", "Opponent", "Challenger", "Rival"],
    correctAnswer: 3,
  },
  {
    id: 24,
    text: "Find out a word similar in meaning to 'a punishment for breaking a law or a rule'.",
    options: ["Penalty", "Forfeit", "Crime", "Damage"],
    correctAnswer: 2,
  },
  {
    id: 25,
    text: "Gandhi said, 'I disliked both'. What does 'both' refer to here?",
    options: [
      "Sanskrit and Persian",
      "Football and Cricket",
      "Cricket and Gymnastics",
      "None of the above",
    ],
    correctAnswer: 0,
  },
  {
    id: 26,
    text: "What did Gandhi never have from the school?",
    options: ["Scholarships", "Prizes", "A bad certificate", "A character certificate"],
    correctAnswer: 2,
  },
  {
    id: 27,
    text: "What did Gandhi consider unbearable for him?",
    options: [
      "Winning prizes",
      "Obtaining scholarships",
      "The least little blemish",
      "Meriting a certificate",
    ],
    correctAnswer: 2,
  },
  {
    id: 28,
    text: "Gandhi said that there was another incident during the time when he was in seventh standard. What was the another incident?",
    options: [
      "He was astonished whenever he won prizes and scholarships",
      "When he merited a rebuke it was unbearable for him",
      "He didn't so much mind the punishment",
      "The headmaster made gymnastics and cricket compulsory for the boys of upper standard",
    ],
    correctAnswer: 3,
  },
  {
    id: 29,
    text: "What, according to Gandhi, should a man of truth be?",
    options: [
      "A man of honesty",
      "A man of care",
      "A man of discipline",
      "A man of method",
    ],
    correctAnswer: 1,
  },
  {
    id: 30,
    text: "Whenever Gandhi won prizes and scholarships, he became",
    options: ["Disappointed", "Astonished", "Exhausted", "Terrified"],
    correctAnswer: 1,
  },
  {
    id: 31,
    text: "Which standard, according to Gandhi, did the children at school normally receive corporal punishment?",
    options: [
      "The first or second standard",
      "The third or fourth standard",
      "The fifth or sixth standard",
      "The seventh or eighth standard",
    ],
    correctAnswer: 0,
  },
  {
    id: 32,
    text: "Find the word which is similar in meaning to 'not strict'.",
    options: ["Convict", "Lenient", "Kind", "Competition"],
    correctAnswer: 1,
  },
  {
    id: 33,
    text: "There was a sort of rivalry going on between.",
    options: [
      "Headmaster and class teacher",
      "Hindi teacher and Persian teacher",
      "Sanskrit and Persian teachers",
      "Persian and English teachers",
    ],
    correctAnswer: 2,
  },
  {
    id: 34,
    text: "Who grieved when Gandhi sat in the Persian class?",
    options: [
      "Sanskrit teacher",
      "Persian teacher",
      "English teacher",
      "Science teacher",
    ],
    correctAnswer: 0,
  },
  {
    id: 35,
    text: "The Sanskrit teacher disclosed the secret information about Gandhi was that he was a son of",
    options: [
      "A Brahmin father",
      "A Sudra father",
      "A Vaishnava father",
      "A Kshetriya father",
    ],
    correctAnswer: 2,
  },
  {
    id: 36,
    text: "Whose affection did Gandhi never disregard at the high school even after leaving the school?",
    options: [
      "Sanskrit teacher",
      "Persian teacher",
      "English teacher",
      "Science teacher",
    ],
    correctAnswer: 0,
  },
  {
    id: 37,
    text: "The study of Sanskrit helped Gandhi in understanding the sacred books of religion.",
    options: ["Hindu", "Muslim", "Sikh", "Christian"],
    correctAnswer: 0,
  },
  {
    id: 38,
    text: "According to Gandhi, the most sacred books of Hindu religion are written in language.",
    options: ["Hindi", "English", "Sanskrit", "Persian"],
    correctAnswer: 2,
  },
  {
    id: 39,
    text: "Whom did Gandhi thank with gratitude?",
    options: [
      "Sanskrit teacher",
      "Persian teacher",
      "English teacher",
      "Science teacher",
    ],
    correctAnswer: 0,
  },
  {
    id: 40,
    text: "Who assured Gandhi that he would teach him the topics to the best of his ability?",
    options: [
      "Sanskrit teacher",
      "Persian teacher",
      "English teacher",
      "Science teacher",
    ],
    correctAnswer: 0,
  },
  {
    id: 41,
    text: "The notion that good handwriting was not a necessary part of education was retained by Gandhi until he went to",
    options: ["England", "South Africa", "Canada", "Cape Town"],
    correctAnswer: 0,
  },
  {
    id: 42,
    text: "According to the Gandhian philosophy, school children should first be taught the art of",
    options: [
      "Writing letters",
      "Drawing objects",
      "Making things",
      "Painting objects",
    ],
    correctAnswer: 1,
  },
  {
    id: 43,
    text: "What was the amount of scholarship that Gandhi got in Standard-VI?",
    options: ["Rs. 5", "Rs. 7", "Rs. 10", "Rs. 11"],
    correctAnswer: 2,
  },
  {
    id: 44,
    text: "What was the amount of scholarship that Gandhi obtained in Standard-V?",
    options: ["Rs. 5", "Rs. 7", "Rs. 10", "Rs. 4"],
    correctAnswer: 3,
  },
  {
    id: 45,
    text: "What did Gandhi thank more for getting his scholarships?",
    options: ["His merit", "His clock", "His luck", "His lock"],
    correctAnswer: 2,
  },
  {
    id: 46,
    text: "What did Gandhi jealously guard at the High school?",
    options: [
      "His punctuality",
      "His truthfulness",
      "His character",
      "His attendance",
    ],
    correctAnswer: 2,
  },
  {
    id: 47,
    text: "Gandhi didn't focus much on his handwriting during his schooling because he thought that",
    options: [
      "Good handwriting was less important part of education",
      "Good handwriting was not a necessary part of education",
      "Literature was more important than handwriting",
      "None of the above",
    ],
    correctAnswer: 1,
  },
  {
    id: 48,
    text: "Which standard did the headmaster make games and sports compulsory for?",
    options: [
      "Lower standard",
      "Middle standard",
      "Upper standard",
      "Higher standard",
    ],
    correctAnswer: 2,
  },
  {
    id: 49,
    text: "In Which standard did Gandhi get corporal punishment?",
    options: [
      "The first or second standard",
      "The second or third standard",
      "The third or fourth standard",
      "The fourth or fifth standard",
    ],
    correctAnswer: 0,
  },
  {
    id: 50,
    text: "Gandhi said that he was bad in...",
    options: ["Handwriting", "Speaking", "Listening", "Reading"],
    correctAnswer: 0,
  },
  {
    id: 51,
    text: "Who was very popular among the boys of the high school?",
    options: [
      "The Sanskrit Teacher",
      "The English Teacher",
      "The Persian teacher",
      "The Headmaster",
    ],
    correctAnswer: 3,
  },
  {
    id: 52,
    text: "What sorts of certificates, according to Gandhi, were sent to the parents every year?",
    options: [
      "Certificates of progress",
      "Certificates of health",
      "Certificates of proficiency",
      "Certificates of merit",
    ],
    correctAnswer: 0,
  },
  {
    id: 53,
    text: "Gandhi received his early education at______.",
    options: [
      "Rajkot High school",
      "Saurashtra High school",
      "Virani High School",
      "Jay High School",
    ],
    correctAnswer: 0,
  },
  {
    id: 54,
    text: "Which standard did Gandhi win prizes in?",
    options: [
      "After he passed out of Standard II",
      "After he passed out of Standard III",
      "After he passed out of Standard IV",
      "After he passed out of Standard V",
    ],
    correctAnswer: 0,
  },
  {
    id: 55,
    text: "Gandhi passed the matriculation in the year",
    options: ["1886", "1886", "1887", "1888"],
    correctAnswer: 2,
  },
  {
    id: 56,
    text: "Gandhi was good at______.",
    options: ["English", "Hindi", "Sanskrit", "Gujarati"],
    correctAnswer: 0,
  },
  {
    id: 57,
    text: "Gandhi was fair in______.",
    options: ["English", "Hindi", "Sanskrit", "Arithmetic"],
    correctAnswer: 3,
  },
  {
    id: 58,
    text: "Gandhi was weak in______.",
    options: ["English", "Hindi", "Sanskrit", "Geography"],
    correctAnswer: 3,
  },
  {
    id: 59,
    text: "What was one of the reasons for Gandhi's aloofness from attending physical exercise?",
    options: [
      "His shyness",
      "His false notion",
      "His dislike",
      "His carelessness",
    ],
    correctAnswer: 0,
  },
  {
    id: 60,
    text: "The upper standard students were made compulsory to attend________.",
    options: [
      "Gymnastics and badminton",
      "Cricket and volleyball",
      "Gymnastics and cricket",
      "Cricket and football",
    ],
    correctAnswer: 2,
  },
  {
    id: 61,
    text: "Gandhi had the false notion that gymnastics had nothing to do with",
    options: ["Education", "Character", "Handwriting", "Mental training"],
    correctAnswer: 0,
  },
  {
    id: 62,
    text: "Later Gandhi realised that every school curriculum should have equal importance on_______.",
    options: [
      "Physical training",
      "Character building",
      "Good handwriting",
      "Mental training",
    ],
    correctAnswer: 0,
  },
  {
    id: 63,
    text: "As soon as the school closed, Gandhi hurried home to_______.",
    options: [
      "Have his supper",
      "Play with his friends",
      "Serve as nurse to his father",
      "Wash his clothes",
    ],
    correctAnswer: 2,
  },
  {
    id: 64,
    text: "According to Gandhi, compulsory came of his father's service_____.",
    options: ["On the way", "In the way", "At the way", "By the way"],
    correctAnswer: 1,
  },
  {
    id: 65,
    text: "At the high school morning class Gandhi had to attend______.",
    options: ["Saturdays", "Sundays", "Mondays", "Tuesdays"],
    correctAnswer: 0,
  },
  {
    id: 66,
    text: "According to Gandhi, on Saturdays the gymnastics classes were normally held at",
    options: ["10 o'clock", "9 o'clock", "4 o'clock", "3 o'clock"],
    correctAnswer: 2,
  },
  {
    id: 67,
    text: "Gandhi failed to know the exact time for gymnastics class because he had no",
    options: ["Money", "Watch", "Mobile set", "None of these"],
    correctAnswer: 1,
  },
  {
    id: 68,
    text: "What deceived Gandhi on Saturday afternoon when he had to attend the gymnastics?",
    options: ["The watch", "The clouds", "The sun", "Mobile hand set"],
    correctAnswer: 1,
  },
  {
    id: 69,
    text: "Mr Gimi examined the roll on that Gandhi was absent in gymnastics class.",
    options: ["Saturday", "Sunday", "Monday", "Tuesday"],
    correctAnswer: 1,
  },
  {
    id: 70,
    text: "The Headmaster ordered Gandhi to pay a fine of______.",
    options: [
      "Two or three rupees",
      "One or two annas",
      "Three or four paisa",
      "None of these.",
    ],
    correctAnswer: 1,
  },
  {
    id: 71,
    text: "The fine imposed on Gandhi deeply pained him as he was convicted of_______.",
    options: ["Lying", "Depressing", "Terrifying", "Stealing"],
    correctAnswer: 0,
  },
  {
    id: 72,
    text: "Gandhi was exempted from attending exercise because of his______.",
    options: ["Mother", "Father", "Sanskrit teacher", "Persian teacher"],
    correctAnswer: 1,
  },
  {
    id: 73,
    text: "Which subject proved, according to Gandhi, a harder task for him?",
    options: ["English", "Sanskrit", "Hindi", "Persian"],
    correctAnswer: 1,
  },
  {
    id: 74,
    text: "What was the first and last instance of Gandhi's carelessness?",
    options: ["Absence from the gymnastic class", "Absence from the Sanskrit class", "Absence from the Persian class", "Absence from the English class"],
    correctAnswer: 0,
  },
  {
    id: 75,
    text: "Gandhi had the false notion that ______was not a necessary part of education",
    options: [
      "Good handwriting",
      "Good physical training",
      "Good mental training",
      "Good moral training",
    ],
    correctAnswer: 1,
  },
  {
    id: 76,
    text: "Gandhi repented of his neglect having seen in South Africa the good handwriting of",
    options: [
      "Teachers and headmasters",
      "Women and men",
      "Young men and lawyers",
      "Teachers and students",
    ],
    correctAnswer: 2,
  },
  {
    id: 77,
    text: "In the end Gandhi felt that bad handwriting is a sign of________",
    options: [
      "Good education",
      "Perfect education",
      "Imperfect education",
      "Proper education",
    ],
    correctAnswer: 2,
  },
  {
    id: 78,
    text: "According to Gandhi, he could not repair the neglect of his",
    options: ["Childhood", "Boyhood", "Adulthood", "Youth"],
    correctAnswer: 3,
  },
  {
    id: 79,
    text: "According to Gandhi, a child should first be taught_______",
    options: [
      "The art of drawing objects",
      "The art of writing letters",
      "The art of drawing maps",
      "The art of painting pictures",
    ],
    correctAnswer: 0,
  },
  {
    id: 80,
    text: "What method, according to Gandhi, should be followed when a child is taught alphabet?",
    options: ["Listening", "Speaking", "Writing", "Observation"],
    correctAnswer: 3,
  },
  {
    id: 81,
    text: "A child can write a formed hand if he is first taught to draw______.",
    options: [
      "Different objects",
      "Alphabet",
      "Scenery",
      "Natural beauty",
    ],
    correctAnswer: 0,
  },
  {
    id: 82,
    text: "Gandhi had the false notion that",
    options: [
      "Physical exercise had nothing to do with education",
      "Character building was very important",
      "Physical education should not be included in curriculum",
      "None of these",
    ],
    correctAnswer: 0,
  },
  {
    id: 83,
    text: "Which subject proved easier for Gandhi at the high school?",
    options: ["Mathematics", "English", "Sanskrit", "Persian."],
    correctAnswer: 3,
  },
  {
    id: 84,
    text: "According to Gandhi, in Sanskrit everything has to be learnt_____.",
    options: ["By head", "By chest", "By heart", "By memory"],
    correctAnswer: 2,
  },
  {
    id: 85,
    text: "According to Gandhi, in geometry there was nothing to______",
    options: ["Write", "Draw", "Memorise", "Speak"],
    correctAnswer: 2,
  },
  {
    id: 86,
    text: "Gandhi considered that Sanskrit was harder than",
    options: ["Mathematics", "Science", "Persian", "Geometry"],
    correctAnswer: 2,
  },
  {
    id: 87,
    text: "Sanskrit was introduced in when Gandhi",
    options: [
      "Fourth standard",
      "Fifth standard",
      "Sixth standard",
      "Seventh standard",
    ],
    correctAnswer: 0,
  },
  {
    id: 88,
    text: "According to Gandhi, the Persian teacher was very",
    options: [
      "Lenient and considerate",
      "Polite and gentle",
      "Smart and active",
      "None of these",
    ],
    correctAnswer: 0,
  },
  {
    id: 89,
    text: "What tempted Gandhi to sit in the Persian class?",
    options: [
      "Easiness of Persian",
      "Kindness of the Persian teacher",
      "Softness of the language",
      "Both (A) and (B)",
    ],
    correctAnswer: 3,
  },
  {
    id: 90,
    text: "What, according to Gandhiji, was the Persian teacher like?",
    options: ["Very strict", "Lenient", "A disciplinarian", "A hard taskmaster"],
    correctAnswer: 1,
  },
  {
    id: 91,
    text: "What pained Gandhiji deeply?",
    options: [
      "The fine imposed on him",
      "His being convicted of lying",
      "His receiving corporal punishment",
      "His being late for gymnastics class",
    ],
    correctAnswer: 1,
  },
  {
    id: 92,
    text: "How, according to Gandhi, should a child learn his letters?",
    options: [
      "By practice",
      "By observation",
      "By listening to teachers",
      "By writing on a piece of paper",
    ],
    correctAnswer: 1,
  },
  {
    id: 93,
    text: "What was Dorabji Edulji Gimi like?",
    options: [
      "Very affectionate to students",
      "Very unpopular among the boys",
      "A disciplinarian and a good teacher",
      "Quite uninterested in gymnastics",
    ],
    correctAnswer: 2,
  },
  {
    id: 94,
    text: "Iswara Chandra Vidyasagar was a great _____(school)",
    options: ["Scholar", "School", "Schooling", "Scholarship"],
    correctAnswer: 0,
  },
  {
    id: 95,
    text: "Gandhi very______ guarded his character. (jealous)",
    options: ["Jealous", "Jealously", "Jeal", "Jealness"],
    correctAnswer: 1,
  },
  {
    id: 96,
    text: "______is a bad quality. (jealous)",
    options: ["Jealously", "Jealous", "Jealousy", "Jealousness"],
    correctAnswer: 2,
  },
  {
    id: 97,
    text: "You shouldn't be________ of my good name. (jealousy)",
    options: ["Jealousy", "Jealing", "Jealously", "Jealous"],
    correctAnswer: 3,
  },
  {
    id: 98,
    text: "Staring at the girl is an act of _______(blame).",
    options: ["Blame", "Blameful", "Blameness", "Blemish"],
    correctAnswer: 3,
  },
  {
    id: 99,
    text: "The pain is still _______(bear)",
    options: ["Bearable", "Bearing", "Unbearable", "Bear"],
    correctAnswer: 2,
  },
  {
    id: 100,
    text: "The girl wept______ over the death of her mother. (pity)",
    options: ["Pitily", "Piteously", "Piteously", "Pitiably"],
    correctAnswer: 1,
  },
];

export const TEST_CONFIG = {
  title: "JITAN'S ONLINE TEST",
  subtitle: "FOR CLASS 10TH",
  session: "2026–2027 Session",
  subject: "English",
  topic: "At the High School",
  date: "01.09.2026",
  durationMinutes: 90,
  preparedBy: "ASTARANG HIGH SCHOOL, ASTARANG",
};
